### ISSUE TITLE
v1.6 checklist

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#153]
* [x] - new directory structure
 * [ ] - `/dist`, `/x/dist` folders for compiled exports
 * [ ] - browser/minified core exports
 * [ ] - minified individual + aggregate core exports
 * [ ] - rubico/x/ individual + aggregate es exports
 * [ ] - rubico/x/ browser/minified exports
 * [ ] - rubico/x/identity
 * [ ] - rubico/x/noop
 * [ ] - rubico/x/groupBy
 * [ ] - rubico/x/always
 * [ ] - rubico/x/thunkify
 * [ ] - rubico/x/memoize

**Comment by richytong** [comment]
done with https://github.com/a-synchronous/rubico/commit/be0b00cd5625126bd722413820be807464cf1991
